<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EJHI608" failures="1" tests="1" name="Test1" time="0.019" errors="0" timestamp="2023-12-28T23:14:05 IST">
  <testcase classname="testcases.ListenerDemo" name="login" time="0.008">
    <failure type="java.lang.AssertionError" message="Failing the test deliberately">
      <![CDATA[java.lang.AssertionError: Failing the test deliberately
at testcases.ListenerDemo.login(ListenerDemo.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test1 -->
